// Generates src/version.ts from package.json so the exported VERSION constant
// can never drift from the published package version. Runs as the first step of
// `npm run build`; also runnable directly via `npm run gen:version`.
//
// The output is committed (like the other generated sources) and CI regenerates
// it to fail on drift. Don't hand-edit src/version.ts — bump package.json's
// "version" and rebuild instead.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const { version } = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'))

const contents = `// GENERATED by scripts/gen-version.mjs from package.json — do not edit by hand.
// Regenerate with \`npm run gen:version\` (runs automatically on \`npm run build\`).

/**
 * The simpleXRPL package version, generated from \`package.json\` at build.
 * Exposed so callers can report the SDK version in diagnostics.
 */
export const VERSION = '${version}'
`

writeFileSync(join(ROOT, 'src/version.ts'), contents)
console.log(`gen-version: wrote src/version.ts (VERSION = ${version})`)
