// GENERATED by scripts/gen-version.mjs from package.json — do not edit by hand.
// Regenerate with `npm run gen:version` (runs automatically on `npm run build`).

/**
 * The simpleXRPL package version, generated from `package.json` at build.
 * Exposed so callers can report the SDK version in diagnostics.
 */
export const VERSION = '0.1.0'
